description: VRPTW

target:
  service: amlk8s
  name: itpwus2cpucl1
  vc: gcrcpu
  # run "amlt target list amlk8s" to list the names of available AMLK8s targets
  # name: msrresrchvc
  # vc: gcr-singularity-resrch

environment:
  image: lesongdocker:env38
  registry: resrchvc4cr.azurecr.io # any public registry can be specified here
  username: resrchvc4cr
  setup:
    - apt install libffi-dev
    - pip install pulp
    - pip install gym
    - pip install pyyaml
    - pip install elkai
    - pip install wandb
    - pip install nn_builder==0.0.12
    - pip install scikit-network
    - cd baselines/hgs_vrptw; make all; cd ../..

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  local_dir: cvrp_benchmarks/
  remote_dir: cvrp_benchmarks/

# list of jobs to run, we run 2 jobs in this example
jobs:
- name: vrptw_ortec_rl
  sku: C8
  command:
  - python controller_batch.py --instance ortec --static --solver rl --  python solver.py --verbose --solver rl
  - python controller_batch.py --instance ortec --solver rl --  python solver.py --verbose --solver rl --strategy greedy
- name: vrptw_ortec_baseline
  sku: C8
  command:
  - python controller_batch.py --instance ortec --static --solver baseline --  python solver.py --verbose --solver baseline
  - python controller_batch.py --instance ortec --solver baseline --  python solver.py --verbose --solver baseline
  - python controller_batch.py --instance ortec --solver baseline --epoch_tlim 60 --strategy greedy --  python solver.py --verbose --solver baseline --strategy greedy
  - python controller_batch.py --instance ortec --solver baseline --epoch_tlim 60 --strategy random --  python solver.py --verbose --solver baseline --strategy random
  - python controller_batch.py --instance ortec --solver baseline --epoch_tlim 60 --strategy lazy --  python solver.py --verbose --solver baseline --strategy lazy
  - python controller_batch.py --instance ortec --solver baseline --epoch_tlim 60 --strategy heuristic --  python solver.py --verbose --solver baseline --strategy heuristic